### ISSUE TITLE
an Enterprise Graph in full production

### ISSUE THREAD

**Issue by pdacton** [zazuko/knowledge-graph-forum#1]
# What would you like to talk about
At Swatch we kept having to manage more and more IT assets. Ditching the .NET app written by our apprentice, we chose an ***RDF framework*** to discover and link IT assets. ***Going life in spring 2018***, 100 users every day are now happily "surfing" and "googling" linked IT and enterprise assets, deploying new assets, checking the health and then also sending the bill to the customer. With only a small team we happened to build a ***private cloud*** using linked data. We ***love the flexibility*** of the graph, compared to other frameworks on the market. Now we want to re-use the information in the graph to build a recommendation system for IT operations, where we start with bi-partite graph analysis.

# Who might be interested in that (technical audience, management, data scientists, etc.)
Developers, IT operations, RDF specialists, data scientists focusing on graph analytics, DBAs, IT management, ...

# What would you like to know from other participants, what feedback are you looking for
Are there other ***RDF application development frameworks*** available? Are other people combining transactions and knowledge in a graph? What graph databases are performing better? What are good uses for inference? Does somebody have experience with ***deepwalk*** or other algorithms?

# What is your background (name, affiliation, etc)
I'm Pete, I'm with Swatch Group Services for more than 15 years in different roles, now leading and puzzling my platform team with crazy technologies like SPARQL. Always curious and on the lookout for better solutions. Husband, father, micro apple-farmer, historic house hacker, scooter rider. Often you can find me between 6 and 7 at La Werkstadt im Biel.

**Comment by ktk** [comment]
Thanks for the submission, we have enough slots for all proposals so far. Please contact me at adrian.gschwend@zazuko.com for a ticket voucher. Please also make sure that you have travel arrangements in case you come in from further away. We will register your session at the DINAcon page.

Last but not least we will create a speaker-page for you, unless you do not want to have that. It will look like [this](https://dinacon.ch/speakers/bart-van-leeuwen/) for example. You are welcome to send me more information about you on the email above, also including a picture if you like.

Looking forward to have you at the conference!
