### ISSUE TITLE
Semantic Regulation Compliance Checking: A real-world scenario involving urban underground data

### ISSUE THREAD

**Issue by ashleycaselli** [zazuko/knowledge-graph-forum#17]
# What would you like to talk about

We will discuss about the development of a semantic-based automated regulation **compliance checking system (CCS)**

* What a CCS is
* Why a CCS is important
* How a CCS can benefit from RDF

Finally, we will show a prototype using urban underground data of the Geneva canton and regulations that apply on those.

# Who might be interested in that (technical audience, management, data scientists, etc.)

Technical audience, semantic technology experts, knowledge engineers, data scientists.

# What would you like to know from other participants, what feedback are you looking for

Feedbacks of any kind are welcome (the presented work is part of my PhD thesis).

# What is your background (name, affiliation, etc)

PhD student & Research assistant @ [Centre Universitaire d’Informatique (CUI)](https://cui.unige.ch/), University of Geneva.

My research interests focus on geospatial semantic web, with a particular reference to urban data and regulations compliance checking models.

# Would you be open to have the session filmed & published later?

No

**Comment by VladimirAlexiev** [comment]
Hi @ashleycaselli , this topic is similar to our starting project https://cordis.europa.eu/project/id/101056973.
Can you share your thesis, papers or presentations?
Cheers!

**Comment by ashleycaselli** [comment]
Hi @VladimirAlexiev. My PhD is ongoing so there is no final version of the thesis yet. Regarding the publications and presentations, you can find everything on my [personal website](https://ashleycaselli.github.io/). We still have several unpublished work that I can discuss with you about privately, if you have time to chat.
