### ISSUE TITLE
Blue Brain Nexus: A knowledge graph for data-driven science

### ISSUE THREAD

**Issue by MFSY** [zazuko/knowledge-graph-forum#2]
# What would you like to talk about

Digital data deluge, cross-disciplinary and multi-modal scientific investigations along with tremendous available computing power has led to team based, data-driven and data-intensive methods in science. This come with a set of challenges for collecting, integrating, accessing, using, reusing and preserving heterogenous datasets generated from different contexts. As a data-driven project aiming to build biologically detailed digital reconstructions and simulations of the rodent, and ultimately the human brain, the Swiss brain research initiative [Blue Brain Project](https://www.epfl.ch/research/domains/bluebrain/) faces also those challenges. To address them we built and open sourced [Blue Brain Nexus](https://bluebrainnexus.io/), a RDF-based Knowledge Graph platform uniquely combining a flexible graph database, a powerful search engine and a scalable data store under a unified declarative and [W3C SHACL](https://www.w3.org/TR/shacl/) model driven REST API to enable:

* Easy unification and integration of fragmented and disparate data from heterogeneous domains to break data and metadata silos leveraging semantic web formats and languages expressiveness as well as RDF flexibility and schema less nature
* Specification of best practices for data collection, storage and description through high quality metadata using the recent [W3C SHACL specification](https://www.w3.org/TR/shacl/)
* Data lineage and provenance recording and description
* FAIR (Findable, Accessible, Interoperable, Re-usable) data and metadata management

We learned a lot along the way ! From building a production ready Knowledge Graph platform to 
on-boarding and introducing managers, developers and scientists to Semantic Web technologies specially the "painfully simplistic"[1] RDF with its developer friendly (is it ? [2] ) serialisation format [JSON-LD](https://json-ld.org/) as well as the "20 years late [W3C SHACL specification](https://www.w3.org/TR/shacl/)" [1] for validating RDF graph.

Also, RDF and the [W3C SHACL specification](https://www.w3.org/TR/shacl/) raise technical and usage challenges both for users and developers when put in production systems as the recent [W3C Workshop on Web Standardisation for Graph Data](https://www.w3.org/Data/events/data-ws-2019/cfp.html) shows. 

The goal of this session is to present a Blue Brain team effort to implement a RDF and SHACL based Knowledge Graph but more importantly to  present and discuss the challenges faced and lessons learned when building a large scale Knowledge Graph for a data-driven research project like Blue Brain Project. The goal is also for me to share with my colleagues knowledge engineers and Semantic Web practitioners what is it like to be one of the very few knowledge engineers in an entire organisation and how better communicate and provide incentives for adoption of Semantic Web technologies.

# What would you like to know from other participants, what feedback are you looking for
This session is intended for: Developers, Data Engineers and scientists, Knowledge Engineers, managers, Scientists,...

I would like to have feedbacks on the approach taken to combine RDF and SHACL in a declarative and model driven REST API for data integration. Also on the overall technical choices and on the Semantic Web technologies used. I would like to hear not only about other potential use cases that could benefit from RDF and SHACL but also about solutions and best practices to better communicate about Semantic Web technologies to increase their adoption.

# What is your background (name, affiliation, etc)
I'm [Mohameth François Sy](https://www.epfl.ch/research/domains/bluebrain/blue-brain/people/section-managers-group-leaders/mohameth-francois-sy/) a PHD in Information Retrieval and Semantic Web, a Data and Knowledge Engineer as well as the Section Manager of the Data and Knowledge Engineering Section of the Blue Brain Project. Before joining Blue Brain Project, I was a Postdoctoral fellow in the LIG lab of the Grenoble Alpes University, France where I built a Knowledge Graph for  adaptive Learning. I'm fortunate enough to be part of a such ambitious project 5 years now! 

[1] Dan Brickley, Schema.org and Google, Libby Miller, BBC July 
     2017https://book.validatingrdf.com/bookHtml005.html
[2] https://ruben.verborgh.org/blog/2018/12/28/designing-a-linked-data-developer-experience/

**Comment by ktk** [comment]
Thanks for the submission, we have enough slots for all proposals so far. Please contact me at adrian.gschwend@zazuko.com for a ticket voucher. Please also make sure that you have travel arrangements in case you come in from further away. We will register your session at the DINAcon page.

Last but not least we will create a speaker-page for you, unless you do not want to have that. It will look like [this](https://dinacon.ch/speakers/bart-van-leeuwen/) for example. You are welcome to send me more information about you on the email above, also including a picture if you like.

Looking forward to have you at the conference!
