### ISSUE TITLE
Proposal: Bridging the Gap - Connect Knowledge Graphs to the Microsoft Graph

### ISSUE THREAD

**Issue by nagyhel** [zazuko/knowledge-graph-forum#25]
## Talk Title
Bridging the Gap - Connect Knowledge Graphs to the Microsoft Graph

## Session Overview
The Microsoft Graph was developed to provide a unified model for knowledge discovery and content intelligence across the Microsoft ecosystem. Microsoft Syntex and Viva Topics where first products within Microsoft 365 to make use of it. Microsoft Copilot bringing GenAI to the table is also heavily depending on the Microsoft Graph. 

But the Microsoft Graph does not connect well with existing knowledge graphs and taxonomies that are already publicly available or developed for other enterprise applications. With PoolParty for SharePoint, taxonomies created in the PoolParty Semantic Suite can be synchronized directly with the MS Term Store, making them available to all standard features within Microsoft 365 that are based on the Microsoft Graph.

In addition, PoolParty for SharePoint enables automatic tagging of content in SharePoint, supporting content intelligence in SharePoint and M365 by providing high quality metadata and an enhanced search experience with semantic search capabilities typically provided by knowledge graphs. In my talk i want to show what impact this combination can have on the quality of results of GenAI within the MS ecosystem.

## Target Audience
Technical practitioners, Content strategists, Knowledge Graph architects

## Desired Feedback
Feedback
Is that approach relevant for people to complement and improve Copilot? 
Challanges
How to make use of knowledge graphs in the MS ecosystem?

## Speaker Details
Helmut is CPO of Semantic Web Company (SWC), the provider of the PoolParty Semantic Suite. SWC is headquartered in Vienna, Austria, but operates globally. PoolParty Semantic Suite is used by over 200 organizations to provide semantic AI solutions. Helmut is a well-known expert in the field of knowledge management and semantic AI and co-author of “The Knowledge Graph Cookbook”.

## Recording Consent
Yes

## Workshop Potential
No

## Visual Aid for Social Media
![kmworld20](https://github.com/zazuko/knowledge-graph-forum/assets/1513440/f940260f-b2ee-49ec-8df9-10454bb3835d)

**Comment by ktk** [comment]
Thanks for the proposal! I'm finalizing the schedule in the following 1-2 weeks, looks like we are pretty much full already.
