### ISSUE TITLE
Chatbot Application on large Goverment Spatial Knowledge Graph in the Netherlands

### ISSUE THREAD

**Issue by erwinfolmer** [zazuko/knowledge-graph-forum#3]
# What would you like to talk about
Our LOKI chatbot: question and answering based on our government spatial data. It works on our RDF Knowledge Graph.

# Who might be interested in that (technical audience, management, data scientists, etc.)
management; it shows a nice application of knowledge graphs in a government setting.

# What would you like to know from other participants, what feedback are you looking for
choices about data, about presentation

# What is your background (name, affiliation, etc)
Erwin Folmer (Kadaster, University of Twente

**Comment by ktk** [comment]
Thanks for the submission, we have enough slots for all proposals so far. Please contact me at adrian.gschwend@zazuko.com for a ticket voucher. Please also make sure that you have travel arrangements in case you come in from further away. We will register your session at the DINAcon page.

Last but not least we will create a speaker-page for you, unless you do not want to have that. It will look like [this](https://dinacon.ch/speakers/bart-van-leeuwen/) for example. You are welcome to send me more information about you on the email above, also including a picture if you like.

Looking forward to have you at the conference!
