### ISSUE TITLE
SPARQL 1.2: Community group, how to improve sparql

### ISSUE THREAD

**Issue by JervenBolleman** [zazuko/knowledge-graph-forum#5]
# What would you like to talk about

There is a [w3c community group](https://www.w3.org/community/sparql-12/)  for moving the SPARQL standards forward. This a session on what is being discussed in the CG and what can be done at a CG level. We will also talk about how you can get involved and what is already being done.

# Who might be interested in that (technical audience, management, data scientists, etc.)
Anyone whom ever wrote a SPARQL query.

# What would you like to know from other participants, what feedback are you looking for
Ideas we have not thought about. Your pain points, hopes and regrets.

# What is your background (name, affiliation, etc)
Jerven Bolleman, as co-lead for the w3c community group.

**Comment by ktk** [comment]
Thanks for the submission, we have enough slots for all proposals so far. Please contact me at adrian.gschwend@zazuko.com for a ticket voucher. Please also make sure that you have travel arrangements in case you come in from further away. We will register your session at the DINAcon page.

Last but not least we will create a speaker-page for you, unless you do not want to have that. It will look like [this](https://dinacon.ch/speakers/bart-van-leeuwen/) for example. You are welcome to send me more information about you on the email above, also including a picture if you like.

Looking forward to have you at the conference!
